title: CHRISTINA GORDON
logo: /images/profile.jpeg
description: Hi! My name is Christina and welcome to my page, my domain and where you can learn more about me.
show_downloads: true
#remote_theme: pages-themes/minimal@v0.2.0
remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme 
